export default {
  books: [
    {
      order: 1,
      title: "Génesis",
      section: "Pentateuco",
      parte: "Antiguo Testamento",
      abbreviation: "Gn",
      chapters: 50,
    },
    {
      order: 2,
      title: "Éxodo",
      section: "Pentateuco",
      parte: "Antiguo Testamento",
      abbreviation: "Ex",
      chapters: 40,
    },
    {
      order: 3,
      title: "Levítico",
      section: "Pentateuco",
      parte: "Antiguo Testamento",
      abbreviation: "Lv",
      chapters: 27,
    },
    {
      order: 4,
      title: "Números",
      section: "Pentateuco",
      parte: "Antiguo Testamento",
      abbreviation: "Nm",
      chapters: 36,
    },
    {
      order: 5,
      title: "Deuteronomio",
      section: "Pentateuco",
      parte: "Antiguo Testamento",
      abbreviation: "Dt",
      chapters: 34,
    },
    {
      order: 6,
      title: "Josué",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "Jos",
      chapters: 24,
    },
    {
      order: 7,
      title: "Jueces",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "Jue",
      chapters: 21,
    },
    {
      order: 8,
      title: "Rut",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "Rt",
      chapters: 4,
    },
    {
      order: 9,
      title: "1 Samuel",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "1 S",
      chapters: 31,
    },
    {
      order: 10,
      title: "2 Samuel",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "2 S",
      chapters: 24,
    },
    {
      order: 11,
      title: "1 Reyes",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "1 R",
      chapters: 22,
    },
    {
      order: 12,
      title: "2 Reyes",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "2 R",
      chapters: 25,
    },
    {
      order: 13,
      title: "1 Crónicas",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "1 Cr",
      chapters: 29,
    },
    {
      order: 14,
      title: "2 Crónicas",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "2 Cr",
      chapters: 36,
    },
    {
      order: 15,
      title: "Esdras",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "Esd",
      chapters: 10,
    },
    {
      order: 16,
      title: "Nehemías",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "Neh",
      chapters: 13,
    },
    {
      order: 17,
      title: "Ester",
      section: "Históricos",
      parte: "Antiguo Testamento",
      abbreviation: "Est",
      chapters: 10,
    },
    {
      order: 18,
      title: "Job",
      section: "Poéticos y Sapienciales",
      parte: "Antiguo Testamento",
      abbreviation: "Job",
      chapters: 42,
    },
    {
      order: 19,
      title: "Salmos",
      section: "Poéticos y Sapienciales",
      parte: "Antiguo Testamento",
      abbreviation: "Sal",
      chapters: 150,
    },
    {
      order: 20,
      title: "Proverbios",
      section: "Poéticos y Sapienciales",
      parte: "Antiguo Testamento",
      abbreviation: "Pr",
      chapters: 31,
    },
    {
      order: 21,
      title: "Eclesiastés",
      section: "Poéticos y Sapienciales",
      parte: "Antiguo Testamento",
      abbreviation: "Ec",
      chapters: 12,
    },
    {
      order: 22,
      title: "Cantares",
      section: "Poéticos y Sapienciales",
      parte: "Antiguo Testamento",
      abbreviation: "Cant",
      chapters: 8,
    },
    {
      order: 23,
      title: "Isaías",
      section: "Profetas Mayores",
      parte: "Antiguo Testamento",
      abbreviation: "Is",
      chapters: 66,
    },
    {
      order: 24,
      title: "Jeremías",
      section: "Profetas Mayores",
      parte: "Antiguo Testamento",
      abbreviation: "Jer",
      chapters: 52,
    },
    {
      order: 25,
      title: "Lamentaciones",
      section: "Profetas Mayores",
      parte: "Antiguo Testamento",
      abbreviation: "Lm",
      chapters: 5,
    },
    {
      order: 26,
      title: "Ezequiel",
      section: "Profetas Mayores",
      parte: "Antiguo Testamento",
      abbreviation: "Eze",
      chapters: 48,
    },
    {
      order: 27,
      title: "Daniel",
      section: "Profetas Mayores",
      parte: "Antiguo Testamento",
      abbreviation: "Da",
      chapters: 12,
    },
    {
      order: 28,
      title: "Oseas",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Os",
      chapters: 14,
    },
    {
      order: 29,
      title: "Joel",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Jl",
      chapters: 3,
    },
    {
      order: 30,
      title: "Amós",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Am",
      chapters: 9,
    },
    {
      order: 31,
      title: "Abdías",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Abd",
      chapters: 1,
    },
    {
      order: 32,
      title: "Jonás",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Jon",
      chapters: 4,
    },
    {
      order: 33,
      title: "Miqueas",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Miq",
      chapters: 7,
    },
    {
      order: 34,
      title: "Nahúm",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Nah",
      chapters: 3,
    },
    {
      order: 35,
      title: "Habacuc",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Hab",
      chapters: 3,
    },
    {
      order: 36,
      title: "Sofonías",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Sof",
      chapters: 3,
    },
    {
      order: 37,
      title: "Hageo",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Hag",
      chapters: 2,
    },
    {
      order: 38,
      title: "Zacarías",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Zac",
      chapters: 14,
    },
    {
      order: 39,
      title: "Malaquías",
      section: "Profetas Menores",
      parte: "Antiguo Testamento",
      abbreviation: "Mal",
      chapters: 4,
    },
    {
      order: 40,
      title: "Mateo",
      section: "Evangelios",
      parte: "Nuevo Testamento",
      abbreviation: "Mt",
      chapters: 28,
    },
    {
      order: 41,
      title: "Marcos",
      section: "Evangelios",
      parte: "Nuevo Testamento",
      abbreviation: "Mr",
      chapters: 16,
    },
    {
      order: 42,
      title: "Lucas",
      section: "Evangelios",
      parte: "Nuevo Testamento",
      abbreviation: "Lc",
      chapters: 24,
    },
    {
      order: 43,
      title: "Juan",
      section: "Evangelios",
      parte: "Nuevo Testamento",
      abbreviation: "Jn",
      chapters: 21,
    },
    {
      order: 44,
      title: "Hechos",
      section: "Historicos",
      parte: "Nuevo Testamento",
      abbreviation: "Hch",
      chapters: 28,
    },
    {
      order: 45,
      title: "Romanos",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Ro",
      chapters: 16,
    },
    {
      order: 46,
      title: "1 Corintios",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "1Co",
      chapters: 16,
    },
    {
      order: 47,
      title: "2 Corintios",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "2Co",
      chapters: 13,
    },
    {
      order: 48,
      title: "Galatas",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Gal",
      chapters: 6,
    },
    {
      order: 49,
      title: "Efesios",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Ef",
      chapters: 6,
    },
    {
      order: 50,
      title: "Filipenses",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Flp",
      chapters: 4,
    },
    {
      order: 51,
      title: "Colosenses",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Col",
      chapters: 4,
    },
    {
      order: 52,
      title: "1 Tesalonicenses",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "1Ts",
      chapters: 5,
    },
    {
      order: 53,
      title: "2 Tesalonicenses",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "2Ts",
      chapters: 3,
    },
    {
      order: 54,
      title: "1 Timoteo",
      section: "Epistolas Pastorales",
      parte: "Nuevo Testamento",
      abbreviation: "1Ti",
      chapters: 6,
    },
    {
      order: 55,
      title: "2 Timoteo",
      section: "Epistolas Pastorales",
      parte: "Nuevo Testamento",
      abbreviation: "2Ti",
      chapters: 4,
    },
    {
      order: 56,
      title: "Tito",
      section: "Epistolas Pastorales",
      parte: "Nuevo Testamento",
      abbreviation: "Tit",
      chapters: 3,
    },
    {
      order: 57,
      title: "Filemón",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Flm",
      chapters: 1,
    },
    {
      order: 58,
      title: "Hebreos",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Heb",
      chapters: 13,
    },
    {
      order: 59,
      title: "Santiago",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Stg",
      chapters: 5,
    },
    {
      order: 60,
      title: "1 Pedro",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "1Pe",
      chapters: 5,
    },
    {
      order: 61,
      title: "2 Pedro",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "2Pe",
      chapters: 3,
    },
    {
      order: 62,
      title: "1 Juan",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "1Jn",
      chapters: 5,
    },
    {
      order: 63,
      title: "2 Juan",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "2Jn",
      chapters: 1,
    },
    {
      order: 64,
      title: "3 Juan",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "3Jn",
      chapters: 1,
    },
    {
      order: 65,
      title: "Judas",
      section: "Epistolas",
      parte: "Nuevo Testamento",
      abbreviation: "Jud",
      chapters: 1,
    },
    {
      order: 66,
      title: "Apocalipsis",
      section: "Profecía",
      parte: "Nuevo Testamento",
      abbreviation: "Ap",
      chapters: 22,
    },
  ],
}
